version: '3.7'
services:
  backend:
    build: .
    container_name: tutor_chatbot_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_URL=${DATABASE_URL}
      - API_KEY=${API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - VALID_COURSE_CODE=${VALID_COURSE_CODE}
      - FRONTEND_URL=${FRONTEND_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    volumes:
      - ./logs:/app/logs
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
   
